image: golang:1.14

stages:
  - test

repository_and_service_tests:
  stage: test
  image: tmaier/docker-compose # or use docker:latest and uncomment stuff in before_script
  tags:
    - dind
  variables:
    GOROOT: "/usr/lib/go"
    GOPATH: "/go"
  before_script:
    - apk update && apk add bash git make musl-dev go gcc libc-dev librdkafka-dev # py-pip python-dev libffi-dev openssl-dev gcc libc-dev
    #- pip install docker-compose
    - export PATH="/go/bin:$PATH"
  script:
    - export HOST_IP=$(grep 'docker' /etc/hosts | head -n 1 | sed -n 's/\(\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\).*/\1/p')
    - echo HOST_IP=$HOST_IP
    - go test -tags musl -v ./...
